"""Fixtures for real smoke receipt assertions; these never launch a scanner."""
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location("scanner_local_validation", Path(__file__).parents[1] / "scripts" / "validate_scanner_local.py")
validation = importlib.util.module_from_spec(spec)
spec.loader.exec_module(validation)


class ScannerLocalEvidenceTests(unittest.TestCase):
    def test_multihost_print_assertions_reject_missing_split_and_duplicate_evidence(self):
        from types import SimpleNamespace
        from unittest.mock import patch
        addresses = [f"127.0.0.{index}" for index in range(4)]
        pages = [f"▼ {address}\nPorts\n43531" for address in addresses]
        pages[-1] += "\nReport generated by Pentest Factory GmbH"
        def reader(texts):
            return SimpleNamespace(pages=[SimpleNamespace(extract_text=lambda text=text: text) for text in texts])
        with patch('pypdf.PdfReader', return_value=reader(pages)):
            proof = validation.validate_multihost_pdf(b"fixture", addresses, 43531)
            self.assertEqual(proof['host_heading_count'], 4)
            self.assertTrue(proof['footer_with_results'])
        failures = [pages[1:], pages + [pages[0]],
                    [pages[0].replace('Ports', ''), *pages[1:]],
                    [pages[0].replace('43531', ''), *pages[1:]],
                    [*pages[:-1], pages[-1].split('Report generated by')[0], 'Report generated by'],
                    [*pages[:-1], pages[-1].split('Report generated by')[0]],
                    pages + ['Report generated by']]
        for texts in failures:
            with self.subTest(texts=texts), patch('pypdf.PdfReader', return_value=reader(texts)):
                with self.assertRaises(RuntimeError):
                    validation.validate_multihost_pdf(b"fixture", addresses, 43531)

    def test_repeat_coverage_requires_exact_loopback_and_command_provenance(self):
        import copy
        comparison = {"coverage": {"comparable": True, "reasons": [],
            "previous_targets": ["127.0.0.1/32"], "current_targets": ["127.0.0.1/32"]},
            "previous_run": {"covered_targets_source": "successful_daedalus_single_ip_command"},
            "current_run": {"covered_targets_source": "successful_daedalus_single_ip_command"}}
        validation.validate_loopback_comparison_coverage(comparison)
        for change in (lambda c: c['coverage'].update(comparable=False),
                       lambda c: c['coverage'].update(current_targets=['127.0.0.0/8']),
                       lambda c: c['coverage'].update(reasons=['incomplete']),
                       lambda c: c['current_run'].clear()):
            bad = copy.deepcopy(comparison)
            change(bad)
            with self.assertRaises(RuntimeError):
                validation.validate_loopback_comparison_coverage(bad)

    def test_controlled_listener_change_requires_exact_confirmed_observation(self):
        import copy
        comparison = {"available": True, "coverage": {"comparable": True, "reasons": [],
            "previous_targets": ["127.0.0.1/32"], "current_targets": ["127.0.0.1/32"]},
            "previous_run": {"covered_targets_source": "successful_daedalus_single_ip_command"},
            "current_run": {"covered_targets_source": "successful_daedalus_single_ip_command"},
            "counts": {"hosts_added": 0, "hosts_removed": 0, "hosts_not_observed": 0,
                       "port_changes": 1, "newly_observed_ports": 0, "reported_port_changes": 1,
                       "confirmed_removed_ports": 0},
            "port_changes": [{"host": "127.0.0.1", "protocol": "tcp", "port": 12345,
                "change": "state_service_changed", "confirmed": True, "before": {"state": "open"}, "after": {"state": "closed"}}]}
        validation.validate_listener_change(comparison, 12345)
        for mutate in (lambda c: c.update(available=False), lambda c: c.update(truncated=True),
                       lambda c: c["counts"].update(reported_port_changes=0),
                       lambda c: c["port_changes"][0].update(confirmed=False),
                       lambda c: c["port_changes"][0].update(change="not_observed"),
                       lambda c: c["port_changes"][0].update(host="192.168.1.1"),
                       lambda c: c["port_changes"][0].update(port=80),
                       lambda c: c["port_changes"][0].update(protocol="udp"),
                       lambda c: c["port_changes"][0].update(after={"state": "open"}),
                       lambda c: c["port_changes"][0]["before"].update(state="closed")):
            bad = copy.deepcopy(comparison); mutate(bad)
            with self.assertRaises(RuntimeError): validation.validate_listener_change(bad, 12345)

    def multi_fixture(self):
        previous, current = [], []
        for i in range(4):
            for rows, start, state in ((previous, 1, "open" if i == 1 else "closed"),
                                       (current, 11, "closed")):
                rows.append({"id": start + i, "event_name": "deep_scan_results", "payload": [{
                    "ip": f"127.0.0.{i}", "ports": [{"protocol": "tcp", "port": 12345, "state": state}]}]})
        expected = [f"127.0.0.{i}/32" for i in range(4)]
        comparison = {"available": True, "coverage": {"comparable": True, "reasons": [],
                      "previous_targets": expected, "current_targets": expected},
            "counts": {"hosts_added": 0, "hosts_removed": 0, "hosts_not_observed": 0,
                       "port_changes": 1, "newly_observed_ports": 0, "reported_port_changes": 1, "confirmed_removed_ports": 0},
            "port_changes": [{"host": "127.0.0.1", "protocol": "tcp", "port": 12345,
                "change": "state_service_changed", "confirmed": True, "before": {"state": "open"}, "after": {"state": "closed"}}]}
        for key, rows in (("previous_run", previous), ("current_run", current)):
            comparison[key] = {"selection_version": 3, "selected_result_event_ids": [r["id"] for r in rows],
                "selected_result_event_id": rows[-1]["id"], "xml_coverage": [{"host": f"127.0.0.{i}"} for i in range(4)]}
        return comparison, {"events": previous}, {"events": current}

    def test_multihost_detects_earlier_change_with_unchanged_last_host(self):
        comparison, previous, current = self.multi_fixture()
        validation.validate_listener_change(comparison, 12345, multi_host=True)
        proof = validation.validate_unchanged_last_host(comparison, previous, current)
        self.assertEqual(proof, {"observed_hosts_per_run": 4, "unchanged_last_host": "127.0.0.3", "changed_earlier_host": "127.0.0.1"})
        with self.assertRaises(RuntimeError): validation.validate_listener_change(comparison, 12345)

    def test_multihost_rejects_omitted_results_xml_or_scope(self):
        import copy
        comparison, previous, current = self.multi_fixture()
        for mutate in (lambda c: c["current_run"]["selected_result_event_ids"].pop(),
                       lambda c: c["previous_run"]["xml_coverage"].pop(),
                       lambda c: c["coverage"].update(current_targets=["127.0.0.0/30"]),
                       lambda c: c["current_run"].update(selection_version=2)):
            bad = copy.deepcopy(comparison); mutate(bad)
            with self.assertRaises(RuntimeError): validation.validate_listener_change(bad, 12345, multi_host=True)
        for mutate in (lambda d: d["events"].pop(),
                       lambda d: d["events"][0]["payload"][0].update(ip="192.168.1.1"),
                       lambda d: d["events"][0]["payload"][0].update(ip="127.0.0.1")):
            bad = copy.deepcopy(current); mutate(bad)
            with self.assertRaises(RuntimeError): validation.validate_unchanged_last_host(comparison, previous, bad)

    def test_multihost_refuses_changed_or_unidentified_final_host(self):
        import copy
        comparison, previous, current = self.multi_fixture()
        bad = copy.deepcopy(current); bad["events"][-1]["payload"][0]["ports"][0]["state"] = "open"
        with self.assertRaises(RuntimeError): validation.validate_unchanged_last_host(comparison, previous, bad)
        for last in [12, 999]:
            bad = copy.deepcopy(comparison); bad["current_run"]["selected_result_event_id"] = last
            with self.assertRaises(RuntimeError): validation.validate_unchanged_last_host(bad, previous, current)

    def test_multihost_refuses_unsupported_mode_before_side_effects(self):
        from unittest.mock import patch
        for platform, options in [("darwin", {"repeat_scan": True, "close_listener": True}), ("linux", {}),
                                  ("linux", {"repeat_scan": True, "close_listener": True, "managed_linux": True})]:
            with patch.object(validation.sys, "platform", platform), patch.object(validation.shutil, "which") as lookup:
                with self.assertRaisesRegex(RuntimeError, "Linux repeated listener-change"):
                    validation.validate(Path('/unused'), Path('/unused-receipt'), multi_host=True, **options)
                lookup.assert_not_called()

    def test_multihost_executable_guard_keeps_distinct_xml_and_rejects_other_targets(self):
        import ast, subprocess, sys, tempfile
        source = ast.parse(Path(validation.__file__).read_text())
        template = next(node.args[0] for node in ast.walk(source) if isinstance(node, ast.Call)
                        and isinstance(node.func, ast.Attribute) and node.func.attr == "write_text"
                        and isinstance(node.func.value, ast.Name) and node.func.value.id == "wrapper")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            fake = root / "fake-nmap"
            fake.write_text("#!" + sys.executable + "\nfrom pathlib import Path\nimport sys\nargs=sys.argv[1:]\nif '-oA' in args: Path(args[args.index('-oA')+1]+'.xml').write_text('<nmaprun target=\"'+args[-1]+'\"/>')\n")
            fake.chmod(0o700)
            code = eval(compile(ast.Expression(template), validation.__file__, "eval"), {
                "nmap_python": Path(sys.executable), "nmap": str(fake), "root": root,
                "scan_target": "127.0.0.0/30", "multi_host": True, "listener_port": 12345, "interrupt_bridge": False})
            wrapper = root / "nmap-guard"; wrapper.write_text(code)
            for ip in ["127.0.0.1", "127.0.0.2"]:
                with tempfile.TemporaryDirectory(prefix="nmapui-evidence-") as evidence:
                    destination = Path(evidence) / "scan.xml"
                    result = subprocess.run([sys.executable, str(wrapper), "-T3", "-sV", "-Pn", "-oX", str(destination), ip], capture_output=True, text=True, timeout=10)
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertEqual(destination.read_text(), '<nmaprun target="'+ip+'"/>')
            self.assertTrue((root / 'actual-scan-127.0.0.1.xml').is_file())
            self.assertTrue((root / 'actual-scan-127.0.0.2.xml').is_file())
            before = (root / 'invocations.jsonl').read_bytes()
            for args in [["-T3", "-sV", "-Pn", "127.0.0.4"], ["-T3", "-sV", "-Pn", "192.168.1.1"], ["-sn", "-Pn", "127.0.0.0/8"], []]:
                result = subprocess.run([sys.executable, str(wrapper), *args], capture_output=True, text=True, timeout=10)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn("rejected unexpected scanner arguments", result.stderr)
            self.assertEqual((root / 'invocations.jsonl').read_bytes(), before)

    def test_closed_xml_requires_exact_single_port_and_success(self):
        prefix = '<nmaprun><scaninfo protocol="tcp" numservices="1" services="12345"/><host><status state="up"/><address addr="127.0.0.1"/><ports>'
        suffix = '</ports></host><runstats><finished exit="success"/></runstats></nmaprun>'
        explicit = prefix + '<port portid="12345" protocol="tcp"><state state="closed"/></port>' + suffix
        aggregate = prefix + '<extraports count="1" state="closed"/>' + suffix
        for xml in (explicit, aggregate):
            validation.validate_closed_listener_xml(xml.encode(), 12345)
            for bad in (xml.replace('state="closed"', 'state="open"'), xml.replace('state="up"', 'state="down"'),
                        xml.replace('exit="success"', 'exit="error"'), xml.replace('127.0.0.1', '192.168.1.1'),
                        xml.replace('services="12345"', 'services="80"'), xml.replace('numservices="1"', 'numservices="2"'),
                        xml.replace('protocol="tcp"', 'protocol="udp"')):
                with self.assertRaises(RuntimeError): validation.validate_closed_listener_xml(bad.encode(), 12345)
        for bad in (prefix + suffix, aggregate.replace('count="1"', 'count="2"'),
                    prefix + '<extraports count="1" state="closed"/><port portid="12345" protocol="tcp"><state state="closed"/></port>' + suffix):
            with self.assertRaises(RuntimeError): validation.validate_closed_listener_xml(bad.encode(), 12345)

    def test_listener_change_rejects_unsupported_modes_before_side_effects(self):
        from unittest.mock import patch
        for options in ({}, {"repeat_scan": True, "interrupt_bridge": True}, {"repeat_scan": True, "managed_linux": True}):
            with patch.object(validation.shutil, "which") as lookup:
                with self.assertRaisesRegex(RuntimeError, "ordinary repeated"):
                    validation.validate(Path('/unused'), Path('/unused-receipt'), close_listener=True, **options)
                lookup.assert_not_called()

    def test_real_harness_disables_background_external_audits(self):
        source = Path(validation.__file__).read_text()
        self.assertIn('DAEDALUS_BACKGROUND_WORKERS_ENABLED="false"', source)
        self.assertIn('SELECT COUNT(*) FROM external_check_runs', source)
        self.assertIn('Scanner-only validation unexpectedly ran an external audit', source)

    def test_readiness_refuses_exited_process_before_accepting_response(self):
        from unittest.mock import Mock, patch
        process = Mock()
        process.poll.return_value = 1
        predicate = Mock(return_value=True)
        with patch.object(validation.time, 'sleep') as sleep:
            with self.assertRaisesRegex(RuntimeError, 'exited before readiness'):
                validation.wait_for(predicate, process=process)
        predicate.assert_not_called()
        sleep.assert_not_called()

    def test_readiness_accepts_live_owned_process(self):
        from unittest.mock import Mock
        process = Mock()
        process.poll.return_value = None
        self.assertEqual(validation.wait_for(lambda: 'ready', process=process), 'ready')

    def test_managed_validation_refuses_root_or_non_linux_before_manager_operations(self):
        import sys
        from unittest.mock import patch
        for platform, uid in [('darwin', 501), ('linux', 0)]:
            with patch.object(validation.sys, 'platform', platform), patch.object(validation.os, 'getuid', return_value=uid), patch.object(validation.shutil, 'which', return_value='/usr/bin/nmap'), patch.object(validation.subprocess, 'run') as run:
                with self.assertRaisesRegex(RuntimeError, 'disposable non-root Linux'):
                    validation.validate(Path(sys.executable), Path('/unused-receipt'), managed_linux=True)
                run.assert_not_called()

    def test_managed_validation_refuses_existing_installation_without_running_services(self):
        import sys
        import tempfile
        from unittest.mock import patch
        with tempfile.TemporaryDirectory() as temporary:
            home = Path(temporary)
            (home / '.config/daedalus').mkdir(parents=True)
            with patch.object(validation.sys, 'platform', 'linux'), patch.object(validation.os, 'getuid', return_value=1001), patch.object(validation.Path, 'home', return_value=home), patch.object(validation.shutil, 'which', return_value='/usr/bin/nmap'), patch.object(validation.subprocess, 'run') as run:
                with self.assertRaisesRegex(RuntimeError, 'Existing Daedalus'):
                    validation.validate(Path(sys.executable), home / 'receipt', managed_linux=True)
                run.assert_not_called()

    def test_recovery_requires_exact_original_identity_and_single_side_effect(self):
        import copy
        pending = [{'client_event_id': 'event-1', 'occurred_at': '2026-09-29T10:00:00+00:00', 'source_job_id': 'run-one', 'source_job_type': 'scan', 'event_name': 'job_status'}]
        history = copy.deepcopy(pending)
        history[0]['occurred_at'] = '2026-09-29T10:00:00Z'
        invocation = ['nmap', '-sT', '-p', '12345', '127.0.0.1']
        proof = validation.validate_recovery_evidence(pending, history, 'run-one', [invocation], 12345)
        self.assertEqual(proof['pending_events_recovered'], 1)
        for mutation in (lambda rows: rows.append(copy.deepcopy(rows[0])), lambda rows: rows[0].update(source_job_id='other'), lambda rows: rows[0].update(occurred_at='2026-09-29T10:00:01Z'), lambda rows: rows[0].update(client_event_id='other'), lambda rows: rows[0].update(event_name='other')):
            bad = copy.deepcopy(history)
            mutation(bad)
            with self.assertRaises(RuntimeError): validation.validate_recovery_evidence(pending, bad, 'run-one', [invocation], 12345)
        for invocations in ([], [invocation, invocation]):
            with self.assertRaises(RuntimeError): validation.validate_recovery_evidence(pending, history, 'run-one', invocations, 12345)

    def test_saved_hosts_require_exact_loopback_and_actual_port(self):
        hosts, ports = validation.validate_host_evidence([{"ip": "127.0.0.1", "ports": [{"port": "12345", "protocol": "tcp", "state": "open"}]}], 12345)
        self.assertEqual((len(hosts), len(ports)), (1, 1))
        for payload in ([{"ip": "127.0.0.1", "ports": [{"port": "12345"}]}], [{"ip": "127.0.0.1", "ports": [{"port": "12345", "protocol": "udp", "state": "open"}]}], [], [{"ip": "192.168.1.1", "ports": [{"port": "12345", "protocol": "tcp", "state": "open"}]}], [{"ip": "127.0.0.1", "ports": [{"port": "80"}]}]):
            with self.assertRaises(RuntimeError): validation.validate_host_evidence(payload, 12345)

    def test_actual_xml_requires_host_up_and_listener_open(self):
        xml = '<nmaprun><host><status state="up"/><address addr="127.0.0.1"/><ports><port portid="12345" protocol="tcp"><state state="open"/></port></ports></host></nmaprun>'
        validation.validate_xml_evidence(xml.encode(), 12345)
        for bad in (xml.replace('protocol="tcp"', 'protocol="udp"'), xml.replace('state="open"', 'state="closed"'), xml.replace('state="up"', 'state="down"'), xml.replace('127.0.0.1', '192.168.1.1')):
            with self.assertRaises(RuntimeError): validation.validate_xml_evidence(bad.encode(), 12345)

    def test_grouped_history_requires_exact_run_and_saved_completion(self):
        import copy
        event = {"id": 1, "source_job_id": "run-one", "source_job_type": "scan"}
        detail = {"truncated": False, "run": {"source_job_id": "run-one", "event_count": 2, "status": "completed", "status_evidence_event_id": 2}, "events": [event, {"id": 2, "source_job_id": "run-one", "event_name": "job_status", "payload": {"status": "completed"}}]}
        validation.validate_run_evidence(detail, event)
        for mutation in (lambda d: d.update(truncated=True), lambda d: d["run"].update(event_count=3), lambda d: d["run"].update(status="unknown"), lambda d: d["events"][1].update(source_job_id="other"), lambda d: d["events"][1]["payload"].update(status="running"), lambda d: d["run"].update(group_metadata_conflict=True)):
            bad = copy.deepcopy(detail)
            mutation(bad)
            with self.assertRaises(RuntimeError):
                validation.validate_run_evidence(bad, event)
